### ISSUE TITLE
Investigate LVM Thin Provisioning

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/vanilla-installer#243]
Switching to thin provisioning would allow us to share the space between the 2 roots.

Example
![image](https://github.com/Vanilla-OS/vanilla-installer/assets/9479903/1974618c-5b3a-4081-8a81-567285dddc14)

**Comment by ludvigng** [comment]
Once the logic is in place, would it be in scope to add support for using btrfs subvolumes instead of LVM? Seems like an extra step for btrfs users to add something that the filesystem already provides, and using subvolumes would make it possible to add stuff like deduplication (for really pushing down the size requirement) and snapshotting (additional rollback options for those that want it).
