### ISSUE TITLE
Why 50GB as minimum partition space?

### ISSUE THREAD

**Issue by mskf1383** [Vanilla-OS/vanilla-installer#83]
In the all years I'm using GNU/Linux (Debian, Ubuntu, Mint), I installed it on a less than 32GB patition. Why Vanilla force user to install it on a partition with at least 50GB space?

**Comment by delight-aug** [comment]
That's due to a custom partitioning scheme. From a contributor:
```
20GB - A (Root, Boot partition 1)
20GB - B (Root, Boot partition 2)
Remaining home partition for users data, files, etc. 
```

**Comment by kbdharun** [comment]
> In the all years I'm using GNU/Linux (Debian, Ubuntu, Mint), I installed it on a less than 32GB partition. Why does Vanilla force the user to install it on a partition with at least 50GB space?

Vanilla OS is an immutable distribution the filesystem is read-only and in order to do updates (through `vso`) and installing drivers have a utility known as `abroot` (https://documentation.vanillaos.org/docs/ABRoot/) which allows package installation/ command execution on the host through an atomic transactional model (more on docs). `abroot` requires 2 states which are 2 root, boot partitions taking 20GB each + 10GB is for your data in `home`. The 2 root partitions automatically swap between during reboot. This allows us to do automatic background updates, and much more.

We are planning to shrink it down from 20+20GB  or make it more flexible in future. 

Thanks @delight-aug for adding the comment btw.

**Comment by mskf1383** [comment]
Thanks for your descriptions. So I close this.
